server:
  port: 8761
eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-service.webapps:8761/eureka/
spring:
  profiles:
    active: k8s

