spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/universitdb?useSSL=false
    username: ricky
    password: 190199
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8055
application:
  config:
    foyer-url: http://localhost:8099/api/v1/foyer